name: Deploy Metabase
on:
  push:
    branches:
    - main
    paths:
    - terraform/**
  workflow_dispatch:
    branches:
      - main
    paths:
    - terraform/**
env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
jobs:
  terraform:
    runs-on: ubuntu-latest
    container:
      image: hashicorp/terraform:1.6
    steps:
      - uses: actions/checkout@v2
      - name: Terraform Init
        run: terraform init -chdir=terraform 
      - name: Terraform Validate
        run: terraform validate -chdir=terraform/ 
      - name: Terraform Plan
        run: terraform plan -out=plan.tfplan -chdir=terraform/
      - name: Terraform Apply
        run: terraform apply -auto-approve -input=false -refresh=false -chdir=terraform/