name: Deploy Metabase
on:
  push:
    branches:
    - main
    paths:
    - terraform/**
  workflow_dispatch:
    branches:
      - main
    paths:
    - terraform/**
env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
jobs:
  terraform:
    runs-on: ubuntu-latest
    container:
      image: hashicorp/terraform:0.12.19
    steps:
      - uses: actions/checkout@v2
      - name: Terraform Init
        run: terraform -chdir=terraform init
      - name: Terraform Validate
        run: terraform -chdir=terraform/ validate
      - name: Terraform Plan
        run: terraform -chdir=terraform/ plan -out=plan.tfplan
      - name: Terraform Apply
        run: terraform -chdir=terraform/ apply -auto-approve -input=false -refresh=false